spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"

spring.cloud.stream:
  function:
    definition: entityProcessor
  bindings:
    entityProcessor-in-0:
      destination: web-domains
  kafka:
    bindings:
      entityProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      entityProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        ${KAFKA_HOST}:${KAFKA_PORT}