spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    protobuf:
      serializer: http://schema-registry:8081
      deserializer: http://schema-registry:8081
  properties:
    specific:
      protobuf:
        value:
          type: net.kodar.protobuf.IHelpEntityProtos$IHelpEntity
    schema:
      registry:
        url: http://schema-registry:8081

spring.cloud.stream:
  function:
    definition: entityProcessor
  bindings:
    entityProcessor-in-0:
      destination: web-domains
    entityProcessor-out-0:
      destination: active.web-domains
  kafka:
    bindings:
      entityProcessor-in-0:
        consumer:
          configuration:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value:
              deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      entityProcessor-out-0:
        producer:
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
            value:
              serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer