spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
  properties:
    specific:
      protobuf:
        value:
          type: net.kodar.protobuf.IHelpEntityProtos$IHelpEntity
    schema:
      registry:
        url: http://schema-registry:8081

spring.cloud.stream:
  function:
    definition: consumerService
  bindings:
    consumerService-in-0:
      destination: active.web-domains
  kafka:
    bindings:
      consumerService-in-0:
        consumer:
          configuration:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value:
              deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer