spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"

spring.cloud.stream:
  function:
    definition: consumerService
  bindings:
    consumerService-in-0:
      destination: active.web-domains
  kafka:
    bindings:
      consumerService-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    binder:
      brokers:
        - localhost:19092