spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"

spring.cloud.stream:
  function:
    definition: activeDomainConsumer,inactiveDomainConsumer
  bindings:
    activeDomainConsumer-in-0:
      destination: active.web-domains
    inactiveDomainConsumer-in-0:
      destination: inactive.web-domains
  kafka:
    bindings:
      activeDomainConsumer-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      inactiveDomainConsumer-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    binder:
      brokers:
        ${KAFKA_HOST}:${KAFKA_PORT}